Add message_structure option support
zuazo/chef-handler-sns pull request #10
Opened 2016-12-23 09:43 UTC by d-averkiev

Hello. According to https://github.com/zuazo/chef-handler-sns/issues/9 I've added `MessageStructure` parameter handling and write some documentation.

2016-12-23 09:46 UTC, d-averkiev commented
I know about "lib/chef/handler/sns/config.rb:31:7: C: Module has too many lines. [103/100]" from rubocop. I have no idea how to get rid of it in this case :(

2016-12-23 12:09 UTC, zuazo commented
@d-averkiev thanks for your contribution! 😃 

You can add a `.rubocop.yml` file with the following content:

```yaml
Metrics/ModuleLength:
  Max: 103
```

You can see its documentation [here](https://github.com/bbatsov/rubocop/blob/master/manual/configuration.md).

2016-12-23 13:01 UTC, d-averkiev commented
Done. Thank you.
Seems Travis failed to install some dependencies. But I didn't touch Gemfile or .gemspec.

2016-12-23 18:16 UTC, zuazo requested changes
Thanks for including documentation and all 😉 Only some tests are missing.

2016-12-23 18:16 UTC, zuazo commented on lib/chef/handler/sns/config.rb
> +        end
Could you add some tests [here](https://github.com/zuazo/chef-handler-sns/blob/master/test/test_chef_handler_sns_config.rb#L32) for the `message_structure` method?

Please, skim-read the already existing tests. You should not have trouble understanding them even if you have never done tests before with [minitest](http://docs.seattlerb.org/minitest/). They are very verbose but it does not take long to read them once you have understood one.

Of course, do not hesitate to consult me if you have any doubts.

2017-02-16 17:47 UTC, merged

2017-02-18 17:42 UTC, zuazo commented
Released in [`2.1.0`](https://github.com/zuazo/chef-handler-sns/releases/tag/2.1.0).